### ISSUE TITLE
Wrong predictions

### ISSUE THREAD

**Issue by GianisTsol** [kd2bd/predict#9]
I installed orbitron on my rpi3 and tried to predict a pass of noaa 19 but the time was off by 30 minutes.Help please

**Comment by vijju27** [comment]
Predict by default uses GMT time zone.
The passes are accurate on my RPi3.

**Comment by rawesomeawesome** [comment]
How would one change the time zone? Im getting massively incorrect data for the us east coast.

**Comment by frrobert2** [comment]
I was having a similar issue.  
1.  When you change your station location, exit the program and start it again.  Otherwise, when you look for passes it is still using the previous location.  Quitting and restarting uses the new location.
2. The second issue is east and west are backwards from the normal way.  Longitude in degrees West is positive.
3. Use only four decimal places, I was using more and things went sideways.
4. Time is in UTC
